version: "3.8"
services:
  mariadb:
    image: mariadb:10.9
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: mis
      MARIADB_USER: mis
      MARIADB_PASSWORD: mis
    ports:
      - "3306:3306"
